// auth
export const AUTH_START = 'AUTH_START';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';

// Location
export const CURRENT_LOCATION = 'CURRENT_LOCATION';
export const ALL_CITIES = 'ALL_CITIES';
export const GET_LOCATION = 'GET_LOCATION';
export const GET_SELECTED_LOCATION_START = 'GET_SELECTED_LOCATION_START';
export const GET_SELECTED_LOCATION_FAILED = 'GET_SELECTED_LOCATION_FAILED';
export const GET_SELECTED_LOCATION_SUCCESS = 'GET_SELECTED_LOCATION_SUCCESS';



